### ISSUE TITLE
对AsyncQueue优化

### ISSUE THREAD

**Issue by forconz** [dotnet-campus/AsyncWorkerCollection#50]
**EventHandler**

自定义无参委托FinishedEventHandler
```
internal delegate void FinishedEventHandler();

private event FinishedEventHandler? CurrentFinished;

_asyncQueue.CurrentFinished += CurrentFinished;

private void CurrentFinished()
            {
                _currentFinishedTaskCompletionSource.TrySetResult(true);
            }

_asyncQueue.CurrentFinished -= CurrentFinished;
```

**public void Dispose()**

#region IDisposable Support
            private bool disposedValue = false; // 要检测冗余调用

            protected virtual void Dispose(bool disposing)
            {
                if (!disposedValue)
                {
                    if (disposing)
                    {
                        // 释放托管状态(托管对象)。
                        lock (_asyncQueue)
                        {
                            _currentFinishedTaskCompletionSource.TrySetResult(true);
                            _asyncQueue.CurrentFinished -= CurrentFinished;
                        }
                    }

                    // TODO: 释放未托管的资源(未托管的对象)并在以下内容中替代终结器。
                    // TODO: 将大型字段设置为 null。

                    disposedValue = true;
                }
            }

            // TODO: 仅当以上 Dispose(bool disposing) 拥有用于释放未托管资源的代码时才替代终结器。
            // ~ApiClient()
            // {
            //   // 请勿更改此代码。将清理代码放入以上 Dispose(bool disposing) 中。
            //   Dispose(false);
            // }

            // 添加此代码以正确实现可处置模式。
            public void Dispose()
            {
                // 请勿更改此代码。将清理代码放入以上 Dispose(bool disposing) 中。
                Dispose(true);
                // TODO: 如果在以上内容中替代了终结器，则取消注释以下行。
                // GC.SuppressFinalize(this);
            }
            #endregion

**Comment by lindexi** [comment]
@forconz  这是什么问题？
