### ISSUE TITLE
Task里执行大数据计算内存没有正常释放的情况

### ISSUE THREAD

**Issue by GlodenBoy** [dotnet-campus/AsyncWorkerCollection#74]
版本是最新版。

项目是一个blazor hybird wpf的混合项目，情况是大致这样的：

`TaskMenuNumber `和 `TodoMenuNumber`  类都是task执行类，注册在依赖里，非SingleInstance
![image](https://user-images.githubusercontent.com/2329528/227851518-078db0b9-9df8-44e1-8aee-b9c1f0df8442.png)

`BaseAsyncQueue`是注册成了单例 获取字典中的 AsyncQueue，从而获取到Task。

![image](https://user-images.githubusercontent.com/2329528/227851737-e6c9adeb-965d-4cf3-8681-7feba24d3b43.png)

我在A窗口初始化的时候创建了2个timer，timer里获取队列里的Task进行消费

![image](https://user-images.githubusercontent.com/2329528/227851997-7321dcb3-d108-4fac-a1fb-e05aca1d4b65.png)

出现的问题：
Task里有个大数据的计算每个分类的数量，这个会比较频繁，因为有task变动在别处就会push进入一个队列，让task在do方法里重新计算一下，结果发现只要是触发了Task内存会一直涨，没有释放，task里的do方法是没有返回和引用的，不知道为啥不会释放？

do 方法：

![)4)P4V)@}~6Z9B7X2NL%V0K](https://user-images.githubusercontent.com/2329528/227852559-29545fb2-b304-4924-b465-8e314d2b084e.png)
![M}NZSF1XVC N8S@%ZH)X`45](https://user-images.githubusercontent.com/2329528/227852569-04637f20-e7fb-4244-8cea-d54bc7135749.png)

用dotMemory 工具查看dump文件发现都堆在了二代里，没有GC，具体都是堆在了异步方法里。

![P3J{XA(E)L$@QE $GI8R%YL](https://user-images.githubusercontent.com/2329528/227852354-948ab1d7-9e5a-4d05-8047-2297c0069659.png)
![image](https://user-images.githubusercontent.com/2329528/227853381-8b6cbef3-ceeb-423a-b6cd-e2ff33eede95.png)

和walterlv老哥聊了一下，需要具体查看下啥原因。

由于对性能这方面不是特别熟悉，不知道是不是我用法的问题，理论上在do方法里哪怕用了linq 生成了数据的copy ，方法执行完 应该自动释放掉，哪怕不是立即释放 也会隔一段时间释放，测试是不断上涨，隔了一晚上也没释放，主动GC，也GC不下来。

**Comment by lindexi** [comment]
@GlodenBoy 有没一个简单复现的项目仓库？我根据你的描述分析不出来为什么

**Comment by GlodenBoy** [comment]
> @GlodenBoy 有没一个简单复现的项目仓库？我根据你的描述分析不出来为什么

好，我看看能不能做一个简单的demo 不依赖我的项目数据可以复现我的状况的。

**Comment by GlodenBoy** [comment]
做了一个简单的wpf Demo发现重现不出来，然后一行一行代码注释，初步找到哪行代码导致的，由于我是hybird的项目，blazor页面一个菜单引用了一个全局的菜单类，这个类数据很少，就是几个菜单分类，然后后面有这个分类下的数据number ，这个number是在Task 的do里获取的，类似 ->` 待办 (1000）`这样的东西， 在blazor里 这个数据刷新是需要 `StateHasChanged` 来刷新页面数据，所以我wpf里 给blazor发送了一个事件 
![image](https://user-images.githubusercontent.com/2329528/227865548-54e427d2-b9a7-4f8c-a8c9-2b69fd3c1c47.png)

由于是异步处理 所以刷新的代码是 `InvokeAsync(StateHasChanged)`，结果我发现只要执行了第一个图这个发送给blazor的事件 内存就会涨，不执行就不会。

**Comment by GlodenBoy** [comment]
我拆解了一下，把timer里 Task的逻辑去掉了 只剩 timer里的每秒一次 `InvokeAsync(StateHasChanged)`，发现内存也会缓步上涨，290M的基础，会涨到400多M，但是到这时候会自动GC。如果加上我的task计算逻辑，就会涨到1g2g都不会GC。说明 异步的 StateHasChanged 会上涨内存，只是不知道为啥加上AsyncWorkerCollection的逻辑就不会GC了。

**Comment by lindexi** [comment]
@GlodenBoy 这个 TaskDetailView 存在一些引用没有释放，能否看一下代码？

**Comment by GlodenBoy** [comment]
> @GlodenBoy 这个 TaskDetailView 存在一些引用没有释放，能否看一下代码？

谢谢熙哥，我准备重构一下代码，因为之前的代码确实写的太暴力粗糙了，我准备把数据字段增减，重构修改新增数据部分，并且分批读取数据，看看能不能解决，
